# http://travis-ci.org configuration file
language: cpp
cache: apt

compiler:
  - gcc
  - clang:

sudo: false

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - gcc-4.8
      - g++-4.8
      - lcov

env:
  global:
    - BUILD_RELEASE=${TRAVIS_BUILD_DIR}/build
    - BUILD_COVERAGE=${TRAVIS_BUILDDIR}/coverage
     
before_script:
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"
  # Create build folder
  - mkdir $BUILD_RELEASE
  # Release build
  - cd $BUILD_RELEASE && cmake -DCMAKE_BUILD_TYPE=release ..

script:
  - cd $BUILD_RELEASE && make check
