# http://travis-ci.org configuration file
dist: trusty
language: cpp
sudo: false

branches:
  only:
  - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-4.8
      env:
        - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"
        
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
        
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
        
env:
  global:
    - BUILD_RELEASE=${TRAVIS_BUILD_DIR}/build
    - BUILD_COVERAGE=${TRAVIS_BUILD_DIR}/coverage
    - INSTALL_DIR=${TRAVIS_BUILD_DIR}/install

before_install:
  - eval "${MATRIX_EVAL}"
  - if [ "$CXX" = "g++-4.8" ];
    then
      pip install --user cpp-coveralls;
    fi
  
before_script:
  # Create build folder
  - mkdir $BUILD_RELEASE
  # Build SymEngine
  - |
    cd ${TRAVIS_BUILD_DIR}/build
    git clone --depth 1 https://github.com/symengine/symengine
    git checkout d9ed52871682c0c909673f9e8f82845abd756598
    cd symengine
    cmake . -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} -DBUILD_TESTS=OFF -DBUILD_BENCHMARKS=OFF
    make -j2 install
  # Release build
  - cd $BUILD_RELEASE && cmake -DCMAKE_BUILD_TYPE=release -DCMAKE_PREFIX_PATH=${INSTALL_DIR} ..

script:
  - time make -j2 all
  - cd $BUILD_RELEASE && make check

after_success:
  # If GCC 4.8: compute code coverage and export it to coveralls
  - if [ "$CXX" = "g++-4.8" ];
    then
      cd $TRAVIS_BUILD_DIR;
      mkdir $BUILD_COVERAGE;
      cd $BUILD_COVERAGE;
      cmake -DBUILD_COVERAGE=ON  -DCMAKE_PREFIX_PATH=${INSTALL_DIR} ..;
      make check;
      cd ..;
      coveralls -b $BUILD_COVERAGE --exclude third_party --exclude tests --exclude test/googletest --gcov-options '\-lp';
    fi
