# http://travis-ci.org configuration file
dist: trusty
language: cpp
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-4.8
      env:
        - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"
        
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
        
env:
  global:
    - BUILD_RELEASE=${TRAVIS_BUILD_DIR}/build

before_install:
  - if [ "$CXX" = "g++-4.8" ];
    then
      pip install --user cpp-coveralls
    fi
  
before_script:
  - eval "${MATRIX_EVAL}"
  # Create build folder
  - mkdir $BUILD_RELEASE
  # Release build
  - cd $BUILD_RELEASE && cmake -DCMAKE_BUILD_TYPE=release ..

script:
  - time make -j2 all
  - cd $BUILD_RELEASE && make check
