version: 1.0.{build}

environment:
  matrix:
    - GENERATOR: "Visual Studio 14 2015 Win64"
    - GENERATOR: "Visual Studio 14 2015"
    - GENERATOR: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - GENERATOR: "Visual Studio 15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    
clone_folder: c:\dev\src

install:
  - git submodule update --init --recursive
  
before_build:
# Cut some noise as described here: http://bit.ly/2gUJxhC
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

build_script:
  - cd c:\dev
  - mkdir build_symengine
  - cd build_symengine
  - git clone --depth 1 https://github.com/symengine/symengine
  - cd symengine
  - cmake .  -G"%GENERATOR%" -DCMAKE_INSTALL_PREFIX=c:/dev/install -DBUILD_TESTS=OFF -DBUILD_BENCHMARKS=OFF
  - cmake --build . --config Release --target install
  - cd C:\dev
  - mkdir build
  - cd build
  - cmake -G"%GENERATOR%" -DCMAKE_PREFIX_PATH=c:/dev/install ../src
  - cmake --build . --config Release --target check
