version: 1.0.{build}

environment:
  matrix:
    - GENERATOR: "Visual Studio 12 2013 Win64"
    - GENERATOR: "Visual Studio 12 2013"
    - GENERATOR: "Visual Studio 14 2015 Win64"
    - GENERATOR: "Visual Studio 14 2015"
    - GENERATOR: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - GENERATOR: "Visual Studio 15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    
clone_folder: c:\dev\src

build_script:
  - cd c:\dev
  - mkdir build
  - cd build
  - cmake -G"%GENERATOR%" ../src
  - cmake --build . --config Release --target check
